---
title: "Untitled"
author: "Joshua-Connor Knapp"
date: '`r Sys.Date()`'
output: pdf_document
---
```{r echo=FALSE, message=FALSE, warning=FALSE}
# Necessary packages

rm(list = ls()) 
gc()

library(pacman)
p_load(rmsfuns, tidyverse, tbl2xts, devtools, PerformanceAnalytics, ggplot2, TTR, RcppRoll, xts, fmxdat, knitr)

list.files('code/', full.names = T, recursive = T) %>% .[grepl('.R', .)] %>% as.list() %>% walk(~source(.))
```

```{r}
cncy <- read_rds("data/currencies.rds")
cncy_carry <- read_rds("data/cncy_Carry.rds")
cncy_value <- read_rds("data/cncy_value.rds")
cncyiv <- read_rds("data/cncyIV.rds")
bbdxy <- read_rds("data/bbdxy.rds")
```







```{r echo=FALSE, message=FALSE, warning=FALSE}

# Look at 3 emerging market currencies, and 3 G10 currencies

countries <- c("SouthAfrica", "Mexico", "India","UK", "Japan", "EU")

# Calculate the currency returns (dlog)

fx_change <- cncy %>% 
    mutate(Name = gsub("_Cncy", "", Name),
           Name = gsub("_Inv", "", Name)) %>% 
    dplyr::filter(Name %in% countries) %>% 
    group_by(Name) %>% 
    mutate(Return = log(Price) - log(lag(Price)),
           Scaled_Price = Price - mean(Price, na.rm = T)) %>% 
    dplyr::filter(date >= ymd(20000101)) %>% 
    ungroup() 

fmxdat::finplot(fx_change%>% 
    ggplot() +
    aes(x = date,
        y = Scaled_Price,
        color = Name) +
    geom_line(alpha = 0.5) +
    ggtitle("Currency prices relative to the USD") +
    guides(alpha = "none")) +
    theme_bw()

fmxdat::finplot(fx_change %>% 
    ggplot() +
    aes(x = Return,
        fill = Name) +
    geom_histogram(alpha = 0.5) +
    facet_wrap(facets = ~ Name,
               scales = "free") + 
    ggtitle("Log Returns: Currencies relative to the USD") + 
    guides(fill = "none", alpha = "none")) +
    theme_bw()

```

We see that SA, UK, and Argentina have a clumping together of returns in the positive tail which might bias model estimates. Need to clean returns

```{r}
cleaned_fx_xts <- fx_change %>% 
    tbl_xts(.,
            cols_to_xts = "Return",
            spread_by = "Name") %>% 
    PerformanceAnalytics::Return.clean(.,
                                       method = "boudt",
                                       alpha = 0.01) 

cleaned_fx <- cleaned_fx_xts %>% 
    xts_tbl() %>% 
    pivot_longer(cols = -date,
                 names_to = "Currency",
                 values_to = "Return") %>% 
    group_by(Currency) %>% 
    mutate(Return_Sqr = Return ^ 2,
           Return_Abs = abs(Return)) %>% 
    ungroup()

fmxdat::finplot(cleaned_fx %>% 
    ggplot() +
    aes(x = date,
        y = Return,
        color = Currency) +
    geom_line(alpha = 0.5) +
    facet_wrap(facets = ~ Currency,
               scales = "free") + 
    ggtitle("Currency returns relative to the USD") +
    guides(alpha = "none"),
                y.pct = T, 
                y.pct_acc = 1) +
    theme_bw()

fmxdat::finplot(cleaned_fx %>% 
    ggplot() +
    aes(x = date,
        y = Return_Sqr,
        color = Currency) +
    geom_line(alpha = 0.5) +
    facet_wrap(facets = ~ Currency,
               scales = "free") + 
    ggtitle("Currency returns squared relative to the USD") +
    guides(alpha = "none")) +
    theme_bw()

fmxdat::finplot(cleaned_fx %>% 
    ggplot() +
    aes(x = date,
        y = Return_Abs,
        color = Currency) +
    geom_line(alpha = 0.5) +
    facet_wrap(facets = ~ Currency,
               scales = "free") + 
    ggtitle("Currency returns absolute relative to the USD") +
    guides(alpha = "none")) +
    theme_bw()
```

I'm going to fit a uni-variate GARCH model on just the Rand first

```{r}
sa_garch <- bestGARCH(data = cleaned_fx_xts$SouthAfrica,
                      comp = c("sGARCH","gjrGARCH","eGARCH","apARCH"),
                      garchOrder = c(1, 1), 
                      armaOrder = c(1, 0),
                      fit = "Akaike")
sa_garch$Criteria
plot(sa_garch$gjrGARCH, which = 3)
```
Ok, according to this I am going to do a Go-GARCH

```{r message=FALSE, warning=FALSE}
gogarch <- estimateGOGARCH(data = cleaned_fx_xts,
                           type = "gjrGARCH")

# Now plotting the volatilities

sigma <- gogarch$Sigma
colnames(sigma) <- colnames(cleaned_fx_xts)
sigma <- sigma %>% 
    xts_tbl() %>% 
    pivot_longer(cols = -date,
                 names_to = "Currency",
                 values_to = "Vol") 
fmxdat::finplot(sigma %>% 
    ggplot() +
    geom_line(aes(x = date,
                  y = Vol,
                  color = Currency)) +
    facet_wrap(~ Currency,
               scales = "free_y")) +
    theme_bw()

# And the correlation pairs
# The output here has super kak naming though so adjust with the following function

pairs <- gogarch$TV_Cor

pairs <- renameMGARCH(series = cleaned_fx_xts,
                      pairs = pairs,
                      long = T)

fmxdat::finplot(ggplot(pairs %>% dplyr::filter(grepl("SouthAfrica_", Pairs), !grepl("_SouthAfrica", Pairs))) +
    geom_line(aes(x = date,
                  y = Rho,
                  color = Pairs)) +
        facet_wrap(~ Pairs) +
        
    theme_bw() +
    ggtitle("Go-GARCH: SA"))

# Average vol

sigma %>% 
    group_by(Currency) %>% 
    mutate(Mean_Vol = mean(Vol, na.rm = T)) %>% 
    dplyr::select(-date, -Vol) %>% 
    unique() %>% 
    arrange(desc(Mean_Vol)) %>% 
    kable(caption = "Average Conditional Volatility")




```


