---
title: "Untitled"
author: "Joshua-Connor Knapp"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Necessary packages

rm(list = ls()) 
gc()
library(pacman)
p_load(rmsfuns, tidyverse, tbl2xts, devtools, PerformanceAnalytics, ggplot2, TTR, RcppRoll, xts, knitr, gt)
list.files('code/', full.names = T, recursive = T) %>% .[grepl('.R', .)] %>% as.list() %>% walk(~source(.))
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
portholds <- read_rds("data/Fund_Holds.rds")
portrets <- read_rds("data/Fund_Rets.rds")
bmholds <- read_rds("data/BM_Holds.rds")
bmrets <- read_rds("data/BM_Rets.rds")
```

First i am isolating just the portfolios and converting them to xts format

```{r echo=FALSE, message=FALSE, warning=FALSE}
portfolios <- inner_join(portrets, bmrets, by = "date") %>% 
    dplyr::select(-Portolio) %>% 
    rename(SO = Returns) %>% 
    tbl_xts()
```

With these we can look at the relative risk

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Lets do relative risk first and performance

plot(PerformanceAnalytics::table.SFM(Ra = portfolios$SO,
                                Rb = portfolios$BM, 
                                scale = 12,
                                Rf = 0) %>% 
    rownames_to_column(var = "Estimates") %>% 
    gt(caption = "Table 1"))

plot(PerformanceAnalytics::table.DownsideRisk(R = portfolios,
                                         ci = 0.95,
                                         scale = 12)%>% 
    rownames_to_column(var = "Estimates") %>% 
    gt(caption = "Table 2"))

# Now lets do relative performance

PerformanceAnalytics::chart.Scatter(y = portfolios$SO,
                                    x = portfolios$BM,
                                    main = "Scatter: Snake Oil Funds & Capped SWIX",
                                    ylab = "Snake Oil", 
                                    xlab = "Capped SWIX",
                                    col = "black", 
                                    symbolset = 16)

PerformanceAnalytics::chart.CumReturns(R = portfolios,
                                       geometric = T,
                                       main = "Cumulative Returns",
                                       legend.loc="bottomright",
                                       colorset = c("steelblue", "orange"),
                                       lwd = 1.5)

chart.RollingPerformance(R = portfolios,
                         FUN = "sd",
                         width = 12, 
                         main="Rolling 12-Month Standard Deviation", 
                         legend.loc="bottomleft",
                         colorset = c("steelblue", "orange"),
                         lwd = 1.5)

chart.RollingPerformance(R = portfolios, 
                         width = 12,
                         main="Rolling 12-Month Returns", 
                         legend.loc="bottomleft",
                         colorset = c("steelblue", "orange"),
                         lwd = 1.5)

# Look at information ratio
```
```{r echo=FALSE, message=FALSE, warning=FALSE}
# See the sectoral composition

tickers <- portholds %>% dplyr::select(Tickers) %>% unique() %>% pull(Tickers)

so_holds <- bmholds %>% 
    dplyr::select(-date, -name, -Portfolio) %>% 
    unique() %>% 
    dplyr::filter(Tickers %in% tickers) %>% 
    mutate(Dup = duplicated(Tickers)) %>% 
    dplyr::filter(!Dup == T) %>% 
    dplyr::select(-Dup)

sector_weights <- portholds %>% 
    inner_join(so_holds, by = "Tickers") %>% 
    group_by(date, Sector) %>% 
    mutate(Sector_W = sum(Weight)) %>% 
    dplyr::select(date, Sector, Sector_W) %>% 
    unique() %>% 
    pivot_wider(names_from = Sector,
                values_from = Sector_W) %>% 
    tbl_xts()

PerformanceAnalytics::chart.StackedBar(w = sector_weights,
                                       space = 0)
```

