---
title: "Untitled"
author: "Joshua-Connor Knapp"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Necessary packages

rm(list = ls()) 
gc()

library(pacman)
p_load(rmsfuns, tidyverse, tbl2xts, devtools, PerformanceAnalytics, ggplot2, TTR, RcppRoll, xts)

list.files('code/', full.names = T, recursive = T) %>% .[grepl('.R', .)] %>% as.list() %>% walk(~source(.))
```

```{r message=FALSE, warning=FALSE}
# Loading the data to have a look

indices <- read_rds("data/Cncy_Hedge_Assets.rds")

# Estimate the weights of the index according to specifications

weights <- data.frame(Indices = colnames(indices)[sapply(indices, is.numeric)],
                      Weights = c(0.6 * 0.3, 0.4 * 0.3, 0.6 * 0.7, 0.4 * 0.7))

# Estimating an unhedged index

unhedged_indices <- indices

unhedged_port <- estimatePORT(data = unhedged_indices,
                              size = 1000,
                              months = c(1, 7),
                              weights = weights)

# Now estimating a hedged portfolio
# Need to adjust USD asset returns for rands first

zar <- read_rds("data/Monthly_zar.rds")

zar <- zar %>% 
    mutate(fx_change = value / lag(value) - 1) %>% 
    dplyr::filter(date >= min(indices$date) & date <= max(indices$date)) %>% 
    dplyr::select(-Tickers, -value)

hedged_indices <- unhedged_indices %>% 
    inner_join(zar, by = "date") %>% 
    mutate(MSCI_ACWI = MSCI_ACWI + fx_change + (MSCI_ACWI * fx_change),
           Bbg_Agg = Bbg_Agg + fx_change + (Bbg_Agg * fx_change)) %>% 
    dplyr::select(-fx_change) 

hedged_port <- estimatePORT(data = hedged_indices,
                            size = 1000,
                            months = c(1, 7),
                            weights = weights)
```
