---
title: "Untitled"
author: "Joshua-Connor Knapp"
date: "`r Sys.Date()`"
output: html_document
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Necessary packages

rm(list = ls()) 
gc()

library(pacman)
p_load(rmsfuns, tidyverse, tbl2xts, devtools, PerformanceAnalytics, ggplot2, TTR, RcppRoll, xts)

list.files('code/', full.names = T, recursive = T) %>% .[grepl('.R', .)] %>% as.list() %>% walk(~source(.))
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Loading the ALSI data and getting a look
# Filterig the data to start in 2013 as it when there is the most available data in small caps

data <- read_rds("data/ALSI.rds") %>% 
    dplyr::filter(date > ymd(20131231))

# I was a bit confused by what the J203 and J403 were communicating but summing them together revealed they are the weights for each ticker as they sum to one for each day
# Calculated the indices from this

data %>% group_by(date) %>% summarise(sum(J203))
data %>% group_by(date) %>% summarise(sum(J403))

# First looking at the indices

indices <- data %>% 
    group_by(date) %>% 
    mutate(ALSI = sum(J203 * Return),
           SWIX = sum(J403 * Return)) %>% 
    dplyr::select(date, ALSI, SWIX) %>% 
    unique() %>% 
    arrange(date)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
chart.RollingPerformance(R = indices %>% tbl_xts(),
                         FUN = "sd",
                         width = 120, 
                         main = "Rolling 120 day Standard Deviation", 
                         legend.loc = "bottomleft",
                         colorset = c("steelblue", "orange"))

chart.CumReturns(R = indices%>% tbl_xts(),
                 main = "Portfolios cumulative returns", 
                 legend.loc = "topleft",
                 colorset = c("steelblue", "orange"))

```

```{r echo=FALSE, message=FALSE, warning=FALSE}
exposure <- data %>% 
    group_by(date, Sector) %>% 
    mutate(ALSI = sum(J203),
           SWIX = sum(J403)) %>% 
    ungroup() %>% 
    dplyr::select(date, Sector, ALSI, SWIX) %>% 
    unique() %>% 
    arrange(Sector)

ggarrange(ggplot() + geom_area(data = exposure, aes(x = date, y = ALSI, fill = Sector), alpha = 0.7) + labs(x = "ALSI", y = "") + theme_bw(), 
          ggplot() + geom_area(data = exposure, aes(x = date, y = SWIX, fill = Sector), alpha = 0.7) + labs(x = "SWIX", y = "") +theme_bw(),
          nrow = 1, ncol = 2,
          common.legend = T,
          legend = "bottom")
```
```{r echo=FALSE, message=FALSE, warning=FALSE}
# Stocks by size and sector

data %>% 
    dplyr::select(Tickers, Index_Name, Sector) %>% 
    unique() %>%  
    mutate(Index_Name = ifelse(is.na(Index_Name), "Not Specified", Index_Name)) %>% 
    ggplot() +
    geom_bar(aes(x = Index_Name, 
                 fill = Sector)) +
    labs(title = "Stocks by Size and Sector",
       x = "Index Size",
       y = "Number of Observations") + 
    theme_bw()
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
    dplyr::select(date, Return, Index_Name) %>% 
    dplyr::filter(!is.na(Index_Name)) %>%
    group_by(date, Index_Name) %>% 
    mutate(Perf = mean(Return)) %>% 
    dplyr::select(-Return) %>% 
    unique() %>% 
    pivot_wider(names_from = Index_Name,
                values_from = Perf) %>% 
    tbl_xts() %>% 
    chart.CumReturns(R = .,
                 main = "Index size mean cumulative returns", 
                 legend.loc = "topleft")
data %>% 
    dplyr::select(date, Return, Index_Name) %>% 
    dplyr::filter(!is.na(Index_Name)) %>%
    group_by(date, Index_Name) %>% 
    mutate(Perf = mean(Return)) %>% 
    dplyr::select(-Return) %>% 
    unique() %>% 
    pivot_wider(names_from = Index_Name,
                values_from = Perf) %>% 
    tbl_xts() %>% 
    chart.RollingPerformance(R = .,
                         FUN = "sd",
                         width = 120, 
                         main = "Rolling 120 day Standard Deviation", 
                         legend.loc = "topleft")

```


Now lets make a capped index

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Prep function rebalance data

days <- read_rds("data/Rebalance_days.rds") %>% 
    dplyr::filter(Date_Type == "Reb Trade Day") %>% 
    pull(date)

rebalance <- data %>% 
    dplyr::filter(date %in% days) %>%
    mutate(rebalance_time = format(date, "%Y%B")) %>% 
    dplyr::select(-Return, -Sector, -Index_Name) 

ALSI_Reb <- rebalance %>%  
    rename(tickers = Tickers,
           weight = J203) %>% 
    dplyr::select(-J403)

SWIX_Reb <- rebalance %>%  
    rename(tickers = Tickers,
           weight = J403) %>% 
    dplyr::select(-J203)

# Prep function returns data

returns <- data %>% 
    dplyr::select(date, Return, Tickers) %>% 
    rename(return = Return,
           tickers = Tickers)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
ALSI_Cap1 <- indexCAP(data = returns,
                  rebalance = ALSI_Reb,
                  cap = 0.05)
colnames(ALSI_Cap1)[2] <- "ALSI 5% Cap"
                  
ALSI_Cap2 <- indexCAP(data = returns,
                  rebalance = ALSI_Reb,
                  cap = 0.1)
colnames(ALSI_Cap2)[2] <- "ALSI 10% Cap"

SWIX_Cap1 <- indexCAP(data = returns,
                  rebalance = SWIX_Reb,
                  cap = 0.05)
colnames(SWIX_Cap1)[2] <- "SWIX 5% Cap"
                  
SWIX_Cap2 <- indexCAP(data = returns,
                  rebalance = SWIX_Reb,
                  cap = 0.1)
colnames(SWIX_Cap2)[2] <- "SWIX 10% Cap"

capped_indices <- ALSI_Cap1 %>% 
    inner_join(ALSI_Cap2, by = "date") %>% 
    inner_join(SWIX_Cap1, by = "date") %>% 
    inner_join(SWIX_Cap2, by = "date") %>% 
    inner_join(indices, by = "date") %>% 
    tbl_xts()

chart.CumReturns(R = capped_indices[, c(1, 2, 5)],
                 main = "ALSI cumulative returns", 
                 legend.loc = "topleft")

chart.CumReturns(R = capped_indices[, c(3, 4, 6)],
                 main = "SWIX cumulative returns", 
                 legend.loc = "topleft")

PerformanceAnalytics::table.DownsideRisk(R = capped_indices,
                                         ci = 0.95,
                                         scale = 12)%>% 
    rownames_to_column(var = "Estimates") %>% 
    kable(caption = "Downside Risks")
```

